project:
  type: book
  output-dir: docs

book:
  title: "Introducción a la Telemetría de Grandes Mamíferos"
  reader-mode: true

  page-footer:
    left: |
      Este tutorial fue escrito por Francisco X. Castellanos y generado en <a href="https://quarto.org/">Quarto</a>.
    right: |
      © 2024 Fundación Oso Andino. Todos los derechos reservados.
  cover-image: docs/Figures/cover.png
  favicon: docs/Figures/cover.png
  site-url: https://r4ds.hadley.nz/
  repo-url: https://github.com/hadley/r4ds/

  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo




