project:
  type: book
  output-dir: docs

book:
  title: "Introducción a la Telemetría de Grandes Mamíferos"
  reader-mode: true

  page-footer:
    left: |
      Escrito por <a href="https://xacfran.github.io/digital-resume/">FXC</a> en <a href="https://quarto.org/">Quarto</a>.
    right: |
      © 2024 Fundación Oso Andino. Todos los derechos reservados.
  cover-image: docs/Figures/cover.png
  favicon: docs/Figures/cover.png
  repo-url: https://github.com/Xacfran/intro_telemetry_r
  repo-actions: [issue]
  sidebar:
    tools:
      - icon: globe
        text: "Fundación Oso Andino"
        href: "https://osoandino.org/"

  chapters:
    - index.qmd
    - intro.qmd
    - analisis_data.qmd
    - datos_telemetricos.qmd
    - areas_vida_1.qmd
    - areas_vida_2.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-copy: true