---
format:
  html:
    toc: true
    toc-title: "Contenidos"
    toc-expand: 1
    code-overflow: wrap
editor_options:
  markdown:
    wrap: sentence
    canonical: true
theme: cosmo
---
# Análisis de datos {.unnumbered}

# Importando datos en R

Antes de ingresar nuestros datos, es muy importante indicar a R cuál será nuestro directorio de trabajo o también llamado **Working Directory**. Es decir, debemos establecer la carpeta dentro de la cual se encuentran los archivos a utilizar, y donde se exportarán los que generes durante tu trabajo.

R toma automáticamente un directorio en el cual trabajar. Puedes saber en que directorio estás trabajando con la función `getwd()`.

Existen algunas formas de establecer nuestro  o lugar de trabajo. La primera es de manera manual:
```r
#| eval=FALSE
setwd("~/Curso_R/Estadistica basica")
```
Nota que el símbolo `~` se encuentra al inicio del directorio escrito. Este símbolo
reemplaza al resultado obtenido de la función `getwd`.

La segunda manera de establecer el directorio es presionando las teclas `Ctrl+Shift+H`. Inmediatamente se abrirá una ventana en la que podrás seleccionar manualmente tu directorio.

## Archivos *csv*