---
format:
    html:
        toc: true
        toc-title: "Contenidos"
        toc-expand: 1
        code-overflow: wrap
editor_options:
    markdown:
        wrap: sentence
        canonical: true
---

# Inicio {.unnumbered}

Este es el curso de Introduccion a la Ecología y Telemetria de Grandes mamiferos dictado por la  <a href="https://osoandino.org">Fundación Oso Andino</a>. Puedes enterarte sobre el cronograma de actividades <a href="https://drive.google.com/file/d/17hlpS6ZyRcRVw-YguwXConvJJJ9oZ2c0/view">aquí</a>.

## Código de conducta {.unnumbered}

Debido a la naturaleza del evento, solicitamos mantener una actitud y vocabulario acorde a la actividad, faltas a las reglas del curso y/o problemas de comportamiento podrían provocar que sean expulsados de la sala.

1.  Se les solicita que su plataforma Zoom esté actualizada a la última versión.
2.  Para ingresar a la reunión, coloca tu nombre y apellido seguido de un guion y tu país de origen (**OBLIGATORIO**). Por ejemplo: Francisco Castellanos - Ecuador.
3.  No mantener prendidas las cámaras web ya que pueden ocupar ancho de banda de la actividad y podrían afectar la conferencia de los expositores.
4.	Los micrófonos deben permanecer apagados para evitar interrupciones.
5.	Buscamos que nuestras clases sean interactivas, por lo que alentamos que se encienda el micrófono únicamente para realizar preguntas ocualquier comentario que aporte con al discusión de los temas dictados.

## Expositores

Estudiantes y profesionales brindarán charlas para mostrar el trabajo que llevan a cabo en sus países.

+-------------------+---------------------------------+----------------------------------------------+
| Fecha             | Expositor                       | Tema                                         |
+===================+=================================+==============================================+
| Marzo 1, 2024     | Dra. Diorene Smith Cabellos     | Blindando de la extinción al perezoso pigmeo |
| 11:00 - 11:30     | - Panamá                        |                                              |
|                   |                                 |                                              |
+-------------------+---------------------------------+----------------------------------------------+
| Marzo 4, 2024     | Jorge Brito - Ecuador           | *A definir*                                    |
| 11:00 - 11:30     |                                 |                                              |
|                   |                                 |                                              |
+-------------------+---------------------------------+----------------------------------------------+
| Marzo 5, 2024     | Angela Alviz - Colombia         | Ocupación, patrones de actividad y abundancia|
| 10:30 - 11:00     |                                 | relativa de la danta de tierras bajas        |
|                   |                                 | (*Tapirus terrestris*) en Arauca, Colombia   |
+-------------------+---------------------------------+----------------------------------------------+
| Marzo 5, 2024     | Valentina López - Colombia      | Patrones intersexuales de la conducta de     |
| 11:00 - 11:30     |                                 | marcaje por olor del oso andino (*Tremarctos*|
|                   |                                 | *ornatus*) en el corredor biológico          |
|                   |                                 | Guácharos-Puracé                             |
+-------------------+---------------------------------+----------------------------------------------+
| Marzo 7, 2024     | Christian Loaiza - Ecuador      | El zorro de Séchura en Ecuador situación     |
| 11:00 - 11:30     |                                 | actual y estado de conservación              |
+-------------------+---------------------------------+----------------------------------------------+
: Las horas corresponden al horario de Ecuador (GMT -5)

## Agradecimientos {.unnumbered}

Esta edición del curso ha sido auspiciada por el Instituto Nacional de Biodiversidad y la Universidad Técnica de Cotopaxi.